### PR TITLE
Improvements for allocation tests for 3.0.0

### PR DESCRIPTION
**Pull request by bjhham**
- Updated snapshots
- Added README
- Added method names to the stack traces
- Updated from some deprecated APIs
- Fixed up the HTML report
  - Added a server gradle target because opening the file fails due to CSP
  - Fixed up the styling, added expandable sections for the sites

### CODE REVIEW

**Review by e5l — APPROVED** [review]
nice reports! lgtm

**Comment by e5l** [comment]
btw, what do you think about configuring TeamCity to export web pages with results to the artifacts? It may simplify checking the results

**Comment by bjhham** [comment]
Hmm yeah that would be pretty nice.  I'm thinking the best information would be to just list the sites / classes where there was an increase in the output, since atm there's no sense of history with the snapshot report.  I could also update the report to include the previous version with comparisons, though that would be getting pretty fancy.

**Comment by bjhham** [comment]
Ok so now you can view test results in the report server along with the existing snapshot, and when the test breaks, you'll get this beautiful summary of what changed in memory allocation:

Screenshot 2023-11-29 at 11 43 34

**Comment by e5l** [comment]
Cool! Good job, thank you :)

**Pull request merged**
